import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/Nav";
import Content from "./components/Content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`flex flex-col h-full w-full ${inter.className}`}
        style={{ fontFamily: "'Open Sans', sans-serif" }}
      >
        <Nav />
        <Content>{children}</Content>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
